default:
  serving_arguments:
    args:
    - --uvicorn-log-level=debug
    - --max-model-len=1024
    - --trust-remote-code
    - --distributed-executor-backend=mp
    gpu_count: 1
model-car:
- image: oci://registry.redhat.io/rhelai1/modelcar-granite-3-1-8b-instruct:1.5
  model_output_type: text
  name: granite-3.1-8b-instruct
  serving_arguments:
    args:
    - --uvicorn-log-level=info
    - --max-model-len=2048
    - --trust-remote-code
    - --tensor-parallel-size=1
    - --gpu-memory-utilization=0.90
    gpu_count: 1
